# When set to true; will set up all the repos below before continuing
# to bootstrap; such that no network access is needed
offline: true
assethost_hostname: "foo"

registry_host: "{{ assethost_hostname }}/registry"

# This is used nowhere inside kubespray, only inside this file
# and our own playbooks
ubuntu_repos: "http://{{ assethost_hostname}}/repos"
ubuntu_repo_base_url: "{{ ubuntu_repos }}/ubuntu"
ubuntu_repo_gpgkey: "{{ ubuntu_repos }}/ubuntu/gpg"

docker_ubuntu_repo_base_url: "{{ ubuntu_repos }}/docker-ce"
docker_ubuntu_repo_gpgkey: "{{ ubuntu_repos }}/docker-ce/gpg"
